name: R-CMD-check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    container: rocker/r-ver:4.0.0
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          install.packages(c("devtools", "testthat", "covr"))
          devtools::install_deps(dependencies = TRUE)
      - name: Test package
        run: devtools::test()
      - name: Code Coverage
        run: covr::codecov()
