// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// matrixMultiply
NumericMatrix matrixMultiply(NumericMatrix mat1, NumericMatrix mat2);
RcppExport SEXP _MLRANOVA_matrixMultiply(SEXP mat1SEXP, SEXP mat2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type mat1(mat1SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type mat2(mat2SEXP);
    rcpp_result_gen = Rcpp::wrap(matrixMultiply(mat1, mat2));
    return rcpp_result_gen;
END_RCPP
}
// matrixInverse
NumericMatrix matrixInverse(NumericMatrix mat);
RcppExport SEXP _MLRANOVA_matrixInverse(SEXP matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type mat(matSEXP);
    rcpp_result_gen = Rcpp::wrap(matrixInverse(mat));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_MLRANOVA_matrixMultiply", (DL_FUNC) &_MLRANOVA_matrixMultiply, 2},
    {"_MLRANOVA_matrixInverse", (DL_FUNC) &_MLRANOVA_matrixInverse, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_MLRANOVA(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
