# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Matrix Multiplication
#'
#' Multiplies two matrices.
#' @param mat1 NumericMatrix, the first matrix.
#' @param mat2 NumericMatrix, the second matrix.
#' @return NumericMatrix, the result of multiplying `mat1` and `mat2`.
#' @export
#' @examples
#' mat1 <- matrix(1:4, nrow = 2)
#' mat2 <- matrix(1:4, nrow = 2)
#' matrixMultiply(mat1, mat2)
matrixMultiply <- function(mat1, mat2) {
    .Call('_MLRANOVA_matrixMultiply', PACKAGE = 'MLRANOVA', mat1, mat2)
}

#' Matrix Inverse
#'
#' Calculates the inverse of a matrix.
#' @param mat NumericMatrix, the matrix for which to find the inverse.
#' @return NumericMatrix, the inverse of `mat`.
#' @export
#' @examples
#' mat <- matrix(1:4, nrow = 2)
#' matrixInverse(mat)
matrixInverse <- function(mat) {
    .Call('_MLRANOVA_matrixInverse', PACKAGE = 'MLRANOVA', mat)
}

